ProductBox As CanvasComponent:
    Fill: =RGBA(0, 0, 0, 0)
    Height: =640
    Partner: |-
        ={CompanyName: "Company Name", Country: "US", EmailAddress: "someone@contoso.com", WebAddress: "https://www.example.com", 
         Address: { Building: "123", Street: "Main Street", City: "Redmond", Country: "US", PostalCode: "12345" }, PhoneNumber: "9876543210"}
    Product: |-
        ={ProductID: "0001", Name: "SampleText", Description: "Product description", SupplierID: "0001", SupplierName: "Supplier Name", Price: "101", CurrencyCode: "USD",
        Category: "Category", Height: "10.000", Width: "12.000", Depth: "14.000", DimUnit: "MM", WeightMeasure: "5.00", WeightUnit: "KG", __metadata: {etag: "Etag"}}
    SalesOrder: |-
        ={Note: "This is a really long note", CustomerName: "SAP", GrossAmount: 10000, SalesOrderID: "sdsd-323", BillingStatusDescription: "Initial", CurrencyCode: "EU"}
    Width: =680
    X: =0
    Y: =0
    ZIndex: =1

    soNote As label:
        FontWeight: =FontWeight.Bold
        Height: =41
        Size: =18
        Text: ="Sales Order for " & ProductBox.SalesOrder.CustomerName
        Width: =566
        X: =72
        Y: =23
        ZIndex: =9

    soNote_1 As label:
        FontWeight: =FontWeight.Bold
        Height: =73
        Size: =18
        Text: |-
            ="ID: " & ProductBox.SalesOrder.SalesOrderID & Char(13) &
            "Billing Status: " & ProductBox.SalesOrder.BillingStatusDescription
        VerticalAlign: =VerticalAlign.Top
        Width: =566
        X: =71
        Y: =89
        ZIndex: =10

    Group3 As group:
        Height: =5
        Width: =5
        X: =40
        Y: =40
        ZIndex: =13

        Button1 As button:
            BorderColor: =ColorFade(Button1.Fill, -15%)
            DisabledFill: =RGBA(0, 0, 0, 0)
            DisplayMode: =DisplayMode.Disabled
            Fill: =RGBA(0, 0, 0, 0)
            Height: =138
            HoverBorderColor: =ColorFade(Button1.BorderColor, 20%)
            PressedBorderColor: =Button1.Fill
            PressedColor: =Button1.Fill
            PressedFill: =Button1.Color
            RadiusBottomLeft: =15
            RadiusBottomRight: =15
            RadiusTopLeft: =15
            RadiusTopRight: =15
            Text: =""
            Width: =549
            X: =72
            Y: =169
            ZIndex: =11

        Label1 As label:
            Height: =111
            Text: =ProductBox.SalesOrder.Note
            VerticalAlign: =VerticalAlign.Top
            Width: =515
            X: =89
            Y: =183
            ZIndex: =12

    Group4 As group:
        Height: =5
        Width: =5
        X: =40
        Y: =40
        ZIndex: =17

        Image3 As image:
            Height: =42
            HoverBorderColor: =ColorFade(Image3.BorderColor, 20%)
            HoverFill: =ColorFade(Image3.Fill, 20%)
            Image: ='sap alert'
            PressedBorderColor: =ColorFade(Image3.BorderColor, -20%)
            PressedFill: =ColorFade(Image3.Fill, -20%)
            Visible: =ProductBox.SalesOrder.CurrencyCode <> "USD"
            Width: =42
            X: =72
            Y: =335
            ZIndex: =13

        Label4 As label:
            Text: ="Order currency is not USD"
            Visible: =ProductBox.SalesOrder.CurrencyCode <> "USD"
            Width: =293
            X: =126
            Y: =336
            ZIndex: =16

    Group4_1 As group:
        Height: =5
        Width: =5
        X: =20
        Y: =20
        ZIndex: =19

        Image3_1 As image:
            Height: =42
            HoverBorderColor: =ColorFade(Image3_1.BorderColor, 20%)
            HoverFill: =ColorFade(Image3_1.Fill, 20%)
            Image: ='sap alert'
            PressedBorderColor: =ColorFade(Image3_1.BorderColor, -20%)
            PressedFill: =ColorFade(Image3_1.Fill, -20%)
            Visible: =ProductBox.SalesOrder.GrossAmount > 7000
            Width: =42
            X: =72
            Y: =395
            ZIndex: =17

        Label4_1 As label:
            Text: ="Order amount is high"
            Visible: =ProductBox.SalesOrder.GrossAmount > 7000
            Width: =293
            X: =126
            Y: =396
            ZIndex: =18

    Group4_2 As group:
        Height: =5
        Width: =5
        X: =20
        Y: =20
        ZIndex: =21

        Image3_2 As image:
            Height: =42
            HoverBorderColor: =ColorFade(Image3_2.BorderColor, 20%)
            HoverFill: =ColorFade(Image3_2.Fill, 20%)
            Image: ='sap alert'
            PressedBorderColor: =ColorFade(Image3_2.BorderColor, -20%)
            PressedFill: =ColorFade(Image3_2.Fill, -20%)
            Visible: =ProductBox.SalesOrder.CustomerName = "TECUM"
            Width: =42
            X: =72
            Y: =456
            ZIndex: =19

        Label4_2 As label:
            Text: ="No previous transactions with customer"
            Visible: =ProductBox.SalesOrder.CustomerName = "TECUM"
            Width: =293
            X: =126
            Y: =457
            ZIndex: =20

